#This is for
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  serviceAccountName: jenkins # This allows to rbac permissions to perform operations on cluster.
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true    
  - name: python # This is newly added to use python commands by calling this pod
    image: python:latest
    command:
    - /bin/cat
    tty: true  
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret # Takes the docker login details from k8's secret path mounthed as volume.
        mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret #This volume path is pointing K8's secrets path where we have created k8's secret for docker credentianls to be used by Kanino during run time.
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json  
